name: Metrics
on:
  # Schedule to run every 3 hours
  schedule: [{cron: "0 */3 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ashababnoor
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, scss, jupyter notebook
          plugin_languages_details: bytes-size, percentage
          # plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
